version: "3.7"

services:
  keycloak:
    image: bitnami/keycloak:latest
    container_name: keycloak
    ports:
      - "8088:8080"
    env_file:
      - .env
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
